Support for Toshiba MeP.

diff --git a/sid/component/cgen-cpu/configure b/sid/component/cgen-cpu/configure
--- a/sid/component/cgen-cpu/configure
+++ b/sid/component/cgen-cpu/configure
@@ -465,10 +465,11 @@ ac_includes_default="\
 
 ac_subdirs_all="$ac_subdirs_all arm7t"
 ac_subdirs_all="$ac_subdirs_all m32r"
+ac_subdirs_all="$ac_subdirs_all mep"
 ac_subdirs_all="$ac_subdirs_all mt"
 ac_subdirs_all="$ac_subdirs_all sh"
 ac_subdirs_all="$ac_subdirs_all xstormy16"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL sidtarget_arm SIDTARGET_ARM_TRUE SIDTARGET_ARM_FALSE sidtarget_x86 SIDTARGET_X86_TRUE SIDTARGET_X86_FALSE sidtarget_mips SIDTARGET_MIPS_TRUE SIDTARGET_MIPS_FALSE sidtarget_m32r SIDTARGET_M32R_TRUE SIDTARGET_M32R_FALSE sidtarget_m68k SIDTARGET_M68K_TRUE SIDTARGET_M68K_FALSE sidtarget_mt SIDTARGET_MT_TRUE SIDTARGET_MT_FALSE sidtarget_ppc SIDTARGET_PPC_TRUE SIDTARGET_PPC_FALSE sidtarget_sh SIDTARGET_SH_TRUE SIDTARGET_SH_FALSE sidtarget_sh64 SIDTARGET_SH64_TRUE SIDTARGET_SH64_FALSE sidtarget_xstormy16 SIDTARGET_XSTORMY16_TRUE SIDTARGET_XSTORMY16_FALSE subdirs cpu_subdirs cpu_defs cpu_incl cpu_libs INTLLIBS GUILE LINKS HAVE_LINKS_TRUE HAVE_LINKS_FALSE XSLTPROC HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE SABLOTRON HAVE_SABLOTRON_TRUE HAVE_SABLOTRON_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL sidtarget_arm SIDTARGET_ARM_TRUE SIDTARGET_ARM_FALSE sidtarget_x86 SIDTARGET_X86_TRUE SIDTARGET_X86_FALSE sidtarget_mips SIDTARGET_MIPS_TRUE SIDTARGET_MIPS_FALSE sidtarget_m32r SIDTARGET_M32R_TRUE SIDTARGET_M32R_FALSE sidtarget_m68k SIDTARGET_M68K_TRUE SIDTARGET_M68K_FALSE sidtarget_mep SIDTARGET_MEP_TRUE SIDTARGET_MEP_FALSE sidtarget_mt SIDTARGET_MT_TRUE SIDTARGET_MT_FALSE sidtarget_ppc SIDTARGET_PPC_TRUE SIDTARGET_PPC_FALSE sidtarget_sh SIDTARGET_SH_TRUE SIDTARGET_SH_FALSE sidtarget_sh64 SIDTARGET_SH64_TRUE SIDTARGET_SH64_FALSE sidtarget_xstormy16 SIDTARGET_XSTORMY16_TRUE SIDTARGET_XSTORMY16_FALSE subdirs cpu_subdirs cpu_defs cpu_incl cpu_libs INTLLIBS GUILE LINKS HAVE_LINKS_TRUE HAVE_LINKS_FALSE XSLTPROC HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE SABLOTRON HAVE_SABLOTRON_TRUE HAVE_SABLOTRON_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3678,7 +3679,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3681 "configure"' > conftest.$ac_ext
+  echo '#line 3682 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5499,7 +5500,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5502:" \
+echo "$as_me:5503:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6597,11 +6598,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6600: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6601: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6604: \$? = $ac_status" >&5
+   echo "$as_me:6605: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6859,11 +6860,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6862: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6863: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6866: \$? = $ac_status" >&5
+   echo "$as_me:6867: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6921,11 +6922,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6924: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6928: \$? = $ac_status" >&5
+   echo "$as_me:6929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9161,7 +9162,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9164 "configure"
+#line 9165 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9259,7 +9260,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9262 "configure"
+#line 9263 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11507,11 +11508,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11510: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11511: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11514: \$? = $ac_status" >&5
+   echo "$as_me:11515: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11569,11 +11570,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11572: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11573: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11576: \$? = $ac_status" >&5
+   echo "$as_me:11577: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12938,7 +12939,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12941 "configure"
+#line 12942 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13036,7 +13037,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13039 "configure"
+#line 13040 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13921,11 +13922,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13924: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13928: \$? = $ac_status" >&5
+   echo "$as_me:13929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13983,11 +13984,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13986: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13987: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13990: \$? = $ac_status" >&5
+   echo "$as_me:13991: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16105,11 +16106,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16108: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16109: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16112: \$? = $ac_status" >&5
+   echo "$as_me:16113: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16367,11 +16368,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16370: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16371: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16374: \$? = $ac_status" >&5
+   echo "$as_me:16375: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16429,11 +16430,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16432: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16433: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16436: \$? = $ac_status" >&5
+   echo "$as_me:16437: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18669,7 +18670,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18672 "configure"
+#line 18673 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18767,7 +18768,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18770 "configure"
+#line 18771 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20882,6 +20883,7 @@ sidtarget_x86=$sidtarget_default
 sidtarget_mips=$sidtarget_default
 sidtarget_m32r=$sidtarget_default
 sidtarget_m68k=$sidtarget_default
+sidtarget_mep=$sidtarget_default
 sidtarget_mt=$sidtarget_default
 sidtarget_ppc=$sidtarget_default
 sidtarget_sh=$sidtarget_default
@@ -20897,11 +20899,12 @@ do
       mips*)  sidtarget_mips=1 ;;
       m32r*)  sidtarget_m32r=1 ;;
       m68k*)  sidtarget_m68k=1 ;;
+      mep*)   sidtarget_mep=1 ;;
       mt*)    sidtarget_mt=1 ;;
       powerpc*) sidtarget_ppc=1 ;;
       ppc*)   sidtarget_ppc=1 ;;
       sh64*) sidtarget_sh64=1 ;;
-      sh*) sidtarget_sh=1 ;;
+      sh*)   sidtarget_sh=1 ;;
       xstormy16*) sidtarget_xstormy16=1 ;;
       *)      { echo "$as_me:$LINENO: WARNING: \"Unknown target $targ\"" >&5
 echo "$as_me: WARNING: \"Unknown target $targ\"" >&2;} ;;
@@ -20914,6 +20917,7 @@ case 1 in
   ${sidtarget_mips}) ;;
   ${sidtarget_m32r}) ;;
   ${sidtarget_m68k}) ;;
+  ${sidtarget_mep}) ;;
   ${sidtarget_mt}) ;;
   ${sidtarget_ppc}) ;;
   ${sidtarget_sh}) ;;
@@ -21004,6 +21008,22 @@ fi
 
 echo "$as_me:$LINENO: result: $sidtarget_m68k" >&5
 echo "${ECHO_T}$sidtarget_m68k" >&6
+
+echo "$as_me:$LINENO: checking Toshiba MeP family support" >&5
+echo $ECHO_N "checking Toshiba MeP family support... $ECHO_C" >&6
+
+
+
+if test "x$sidtarget_mep" = x1; then
+  SIDTARGET_MEP_TRUE=
+  SIDTARGET_MEP_FALSE='#'
+else
+  SIDTARGET_MEP_TRUE='#'
+  SIDTARGET_MEP_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $sidtarget_mep" >&5
+echo "${ECHO_T}$sidtarget_mep" >&6
 
 echo "$as_me:$LINENO: checking MT family support" >&5
 echo $ECHO_N "checking MT family support... $ECHO_C" >&6
@@ -21103,6 +21123,13 @@ if test $sidtarget_m32r -eq 1; then
 
 
 subdirs="$subdirs m32r"
+
+fi
+if test $sidtarget_mep -eq 1; then
+	cpu_subdirs="$cpu_subdirs mep"
+
+
+subdirs="$subdirs mep"
 
 fi
 if test $sidtarget_mt -eq 1; then
@@ -21583,6 +21610,13 @@ if test -z "${SIDTARGET_M68K_TRUE}" && test -z "${SIDTARGET_M68K_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_M68K\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"SIDTARGET_M68K\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SIDTARGET_MEP_TRUE}" && test -z "${SIDTARGET_MEP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_MEP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SIDTARGET_MEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22264,6 +22298,9 @@ s,@SIDTARGET_M32R_FALSE@,$SIDTARGET_M32R_FALSE,;t t
 s,@sidtarget_m68k@,$sidtarget_m68k,;t t
 s,@SIDTARGET_M68K_TRUE@,$SIDTARGET_M68K_TRUE,;t t
 s,@SIDTARGET_M68K_FALSE@,$SIDTARGET_M68K_FALSE,;t t
+s,@sidtarget_mep@,$sidtarget_mep,;t t
+s,@SIDTARGET_MEP_TRUE@,$SIDTARGET_MEP_TRUE,;t t
+s,@SIDTARGET_MEP_FALSE@,$SIDTARGET_MEP_FALSE,;t t
 s,@sidtarget_mt@,$sidtarget_mt,;t t
 s,@SIDTARGET_MT_TRUE@,$SIDTARGET_MT_TRUE,;t t
 s,@SIDTARGET_MT_FALSE@,$SIDTARGET_MT_FALSE,;t t
