2005-06-15  Dave Brolley  <brolley@redhat.com>
        Morpho ms1 cpu contributed on behalf of Red Hat
        2004-05-14  Stan Cox  <scox@redhat.com>

        * ms1: New directory.
        * aclocal.m4: Regenerated.
        * Makefile.in: Ditto.
        * configure: Ditto.
        * configure.in: Support added for ms1.
        * compCGEN.cxx: Ditto.

diff --git a/sid/component/cgen-cpu/configure b/sid/component/cgen-cpu/configure
--- a/sid/component/cgen-cpu/configure
+++ b/sid/component/cgen-cpu/configure
@@ -465,8 +465,9 @@ ac_includes_default="\
 
 ac_subdirs_all="$ac_subdirs_all arm7t"
 ac_subdirs_all="$ac_subdirs_all m32r"
+ac_subdirs_all="$ac_subdirs_all ms1"
 ac_subdirs_all="$ac_subdirs_all xstormy16"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL sidtarget_arm SIDTARGET_ARM_TRUE SIDTARGET_ARM_FALSE sidtarget_x86 SIDTARGET_X86_TRUE SIDTARGET_X86_FALSE sidtarget_mips SIDTARGET_MIPS_TRUE SIDTARGET_MIPS_FALSE sidtarget_m32r SIDTARGET_M32R_TRUE SIDTARGET_M32R_FALSE sidtarget_m68k SIDTARGET_M68K_TRUE SIDTARGET_M68K_FALSE sidtarget_ppc SIDTARGET_PPC_TRUE SIDTARGET_PPC_FALSE sidtarget_xstormy16 SIDTARGET_XSTORMY16_TRUE SIDTARGET_XSTORMY16_FALSE subdirs cpu_subdirs cpu_incl cpu_libs cpu_defs INTLLIBS GUILE LINKS HAVE_LINKS_TRUE HAVE_LINKS_FALSE XSLTPROC HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE SABLOTRON HAVE_SABLOTRON_TRUE HAVE_SABLOTRON_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL sidtarget_arm SIDTARGET_ARM_TRUE SIDTARGET_ARM_FALSE sidtarget_x86 SIDTARGET_X86_TRUE SIDTARGET_X86_FALSE sidtarget_mips SIDTARGET_MIPS_TRUE SIDTARGET_MIPS_FALSE sidtarget_m32r SIDTARGET_M32R_TRUE SIDTARGET_M32R_FALSE sidtarget_m68k SIDTARGET_M68K_TRUE SIDTARGET_M68K_FALSE sidtarget_ms1 SIDTARGET_MS1_TRUE SIDTARGET_MS1_FALSE sidtarget_ppc SIDTARGET_PPC_TRUE SIDTARGET_PPC_FALSE sidtarget_xstormy16 SIDTARGET_XSTORMY16_TRUE SIDTARGET_XSTORMY16_FALSE subdirs cpu_subdirs cpu_defs cpu_incl cpu_libs INTLLIBS GUILE LINKS HAVE_LINKS_TRUE HAVE_LINKS_FALSE XSLTPROC HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE SABLOTRON HAVE_SABLOTRON_TRUE HAVE_SABLOTRON_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3676,7 +3677,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3679 "configure"' > conftest.$ac_ext
+  echo '#line 3680 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5497,7 +5498,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5500:" \
+echo "$as_me:5501:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6595,11 +6596,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6598: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6599: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6602: \$? = $ac_status" >&5
+   echo "$as_me:6603: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6857,11 +6858,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6860: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6861: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6864: \$? = $ac_status" >&5
+   echo "$as_me:6865: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6919,11 +6920,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6922: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6923: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6926: \$? = $ac_status" >&5
+   echo "$as_me:6927: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9159,7 +9160,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9162 "configure"
+#line 9163 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9257,7 +9258,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9260 "configure"
+#line 9261 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11505,11 +11506,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11508: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11509: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11512: \$? = $ac_status" >&5
+   echo "$as_me:11513: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11567,11 +11568,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11570: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11571: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11574: \$? = $ac_status" >&5
+   echo "$as_me:11575: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12936,7 +12937,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12939 "configure"
+#line 12940 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13034,7 +13035,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13037 "configure"
+#line 13038 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13919,11 +13920,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13922: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13923: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13926: \$? = $ac_status" >&5
+   echo "$as_me:13927: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13981,11 +13982,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13984: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13985: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13988: \$? = $ac_status" >&5
+   echo "$as_me:13989: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16103,11 +16104,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16106: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16107: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16110: \$? = $ac_status" >&5
+   echo "$as_me:16111: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16365,11 +16366,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16368: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16369: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16372: \$? = $ac_status" >&5
+   echo "$as_me:16373: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16427,11 +16428,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16430: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16431: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16434: \$? = $ac_status" >&5
+   echo "$as_me:16435: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18667,7 +18668,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18670 "configure"
+#line 18671 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18765,7 +18766,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18768 "configure"
+#line 18769 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20879,6 +20880,7 @@ sidtarget_arm=$sidtarget_default
 sidtarget_x86=$sidtarget_default
 sidtarget_mips=$sidtarget_default
 sidtarget_m32r=$sidtarget_default
+sidtarget_ms1=$sidtarget_default
 sidtarget_m68k=$sidtarget_default
 sidtarget_ppc=$sidtarget_default
 sidtarget_xstormy16=$sidtarget_default
@@ -20892,6 +20894,7 @@ do
       mips*)  sidtarget_mips=1 ;;
       m32r*)  sidtarget_m32r=1 ;;
       m68k*)  sidtarget_m68k=1 ;;
+      ms1*) sidtarget_ms1=1 ;;
       powerpc*) sidtarget_ppc=1 ;;
       ppc*)   sidtarget_ppc=1 ;;
       xstormy16*) sidtarget_xstormy16=1 ;;
@@ -20906,6 +20909,7 @@ case 1 in
   ${sidtarget_mips}) ;;
   ${sidtarget_m32r}) ;;
   ${sidtarget_m68k}) ;;
+  ${sidtarget_ms1}) ;;
   ${sidtarget_ppc}) ;;
   ${sidtarget_xstormy16}) ;;
   *) { echo "$as_me:$LINENO: WARNING: No selected sid targets: use --enable-targets or --target" >&5
@@ -20994,6 +20998,22 @@ fi
 echo "$as_me:$LINENO: result: $sidtarget_m68k" >&5
 echo "${ECHO_T}$sidtarget_m68k" >&6
 
+echo "$as_me:$LINENO: checking MS1 family support" >&5
+echo $ECHO_N "checking MS1 family support... $ECHO_C" >&6
+
+
+
+if test "x$sidtarget_ms1" = x1; then
+  SIDTARGET_MS1_TRUE=
+  SIDTARGET_MS1_FALSE='#'
+else
+  SIDTARGET_MS1_TRUE='#'
+  SIDTARGET_MS1_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $sidtarget_ms1" >&5
+echo "${ECHO_T}$sidtarget_ms1" >&6
+
 echo "$as_me:$LINENO: checking PPC family support" >&5
 echo $ECHO_N "checking PPC family support... $ECHO_C" >&6
 
@@ -21046,6 +21066,13 @@ if test $sidtarget_m32r -eq 1; then
 subdirs="$subdirs m32r"
 
 fi
+if test $sidtarget_ms1 -eq 1; then
+	cpu_subdirs="$cpu_subdirs ms1"
+
+
+subdirs="$subdirs ms1"
+
+fi
 if test $sidtarget_xstormy16 -eq 1; then
 	cpu_subdirs="$cpu_subdirs xstormy16"
 
@@ -21058,6 +21085,7 @@ for dir in $cpu_subdirs; do
 	cpu_libs="$cpu_libs $dir/lib$dir.la"
 	cpu_incl="$cpu_incl -I$srcdir/$dir"
 done
+
 
 
 
@@ -21509,6 +21537,13 @@ if test -z "${SIDTARGET_M68K_TRUE}" && test -z "${SIDTARGET_M68K_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_M68K\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"SIDTARGET_M68K\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SIDTARGET_MS1_TRUE}" && test -z "${SIDTARGET_MS1_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_MS1\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SIDTARGET_MS1\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22169,6 +22204,9 @@ s,@SIDTARGET_M32R_FALSE@,$SIDTARGET_M32R_FALSE,;t t
 s,@sidtarget_m68k@,$sidtarget_m68k,;t t
 s,@SIDTARGET_M68K_TRUE@,$SIDTARGET_M68K_TRUE,;t t
 s,@SIDTARGET_M68K_FALSE@,$SIDTARGET_M68K_FALSE,;t t
+s,@sidtarget_ms1@,$sidtarget_ms1,;t t
+s,@SIDTARGET_MS1_TRUE@,$SIDTARGET_MS1_TRUE,;t t
+s,@SIDTARGET_MS1_FALSE@,$SIDTARGET_MS1_FALSE,;t t
 s,@sidtarget_ppc@,$sidtarget_ppc,;t t
 s,@SIDTARGET_PPC_TRUE@,$SIDTARGET_PPC_TRUE,;t t
 s,@SIDTARGET_PPC_FALSE@,$SIDTARGET_PPC_FALSE,;t t
@@ -22177,9 +22215,9 @@ s,@SIDTARGET_XSTORMY16_TRUE@,$SIDTARGET_XSTORMY16_TRUE,;t t
 s,@SIDTARGET_XSTORMY16_FALSE@,$SIDTARGET_XSTORMY16_FALSE,;t t
 s,@subdirs@,$subdirs,;t t
 s,@cpu_subdirs@,$cpu_subdirs,;t t
+s,@cpu_defs@,$cpu_defs,;t t
 s,@cpu_incl@,$cpu_incl,;t t
 s,@cpu_libs@,$cpu_libs,;t t
-s,@cpu_defs@,$cpu_defs,;t t
 s,@INTLLIBS@,$INTLLIBS,;t t
 s,@GUILE@,$GUILE,;t t
 s,@LINKS@,$LINKS,;t t
