2006-10-18  Dave Brolley  <brolley@redhat.com>
        * Contribute the following changes:

        2006-05-11  Dave Brolley  <brolley@redhat.com>

        * configure.in: Add sh support.
        * compCGEN.cxx: #include sh* cpu headers.
        (compCGENListTypes): List hw-cpu-sh*.
        (compCGENCreate): Handle hw-cpu-sh*.
        * sh: New directory.

diff --git a/sid/component/cgen-cpu/configure b/sid/component/cgen-cpu/configure
--- a/sid/component/cgen-cpu/configure
+++ b/sid/component/cgen-cpu/configure
@@ -466,8 +466,9 @@ ac_includes_default="\
 ac_subdirs_all="$ac_subdirs_all arm7t"
 ac_subdirs_all="$ac_subdirs_all m32r"
 ac_subdirs_all="$ac_subdirs_all mt"
+ac_subdirs_all="$ac_subdirs_all sh"
 ac_subdirs_all="$ac_subdirs_all xstormy16"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL sidtarget_arm SIDTARGET_ARM_TRUE SIDTARGET_ARM_FALSE sidtarget_x86 SIDTARGET_X86_TRUE SIDTARGET_X86_FALSE sidtarget_mips SIDTARGET_MIPS_TRUE SIDTARGET_MIPS_FALSE sidtarget_m32r SIDTARGET_M32R_TRUE SIDTARGET_M32R_FALSE sidtarget_m68k SIDTARGET_M68K_TRUE SIDTARGET_M68K_FALSE sidtarget_mt SIDTARGET_MT_TRUE SIDTARGET_MT_FALSE sidtarget_ppc SIDTARGET_PPC_TRUE SIDTARGET_PPC_FALSE sidtarget_xstormy16 SIDTARGET_XSTORMY16_TRUE SIDTARGET_XSTORMY16_FALSE subdirs cpu_subdirs cpu_defs cpu_incl cpu_libs INTLLIBS GUILE LINKS HAVE_LINKS_TRUE HAVE_LINKS_FALSE XSLTPROC HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE SABLOTRON HAVE_SABLOTRON_TRUE HAVE_SABLOTRON_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL sidtarget_arm SIDTARGET_ARM_TRUE SIDTARGET_ARM_FALSE sidtarget_x86 SIDTARGET_X86_TRUE SIDTARGET_X86_FALSE sidtarget_mips SIDTARGET_MIPS_TRUE SIDTARGET_MIPS_FALSE sidtarget_m32r SIDTARGET_M32R_TRUE SIDTARGET_M32R_FALSE sidtarget_m68k SIDTARGET_M68K_TRUE SIDTARGET_M68K_FALSE sidtarget_mt SIDTARGET_MT_TRUE SIDTARGET_MT_FALSE sidtarget_ppc SIDTARGET_PPC_TRUE SIDTARGET_PPC_FALSE sidtarget_sh SIDTARGET_SH_TRUE SIDTARGET_SH_FALSE sidtarget_sh64 SIDTARGET_SH64_TRUE SIDTARGET_SH64_FALSE sidtarget_xstormy16 SIDTARGET_XSTORMY16_TRUE SIDTARGET_XSTORMY16_FALSE subdirs cpu_subdirs cpu_defs cpu_incl cpu_libs INTLLIBS GUILE LINKS HAVE_LINKS_TRUE HAVE_LINKS_FALSE XSLTPROC HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE SABLOTRON HAVE_SABLOTRON_TRUE HAVE_SABLOTRON_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3677,7 +3678,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3680 "configure"' > conftest.$ac_ext
+  echo '#line 3681 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5498,7 +5499,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5501:" \
+echo "$as_me:5502:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6596,11 +6597,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6599: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6600: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6603: \$? = $ac_status" >&5
+   echo "$as_me:6604: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6858,11 +6859,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6861: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6862: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6865: \$? = $ac_status" >&5
+   echo "$as_me:6866: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6920,11 +6921,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6923: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6924: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6927: \$? = $ac_status" >&5
+   echo "$as_me:6928: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9160,7 +9161,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9163 "configure"
+#line 9164 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9258,7 +9259,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9261 "configure"
+#line 9262 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11506,11 +11507,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11509: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11510: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11513: \$? = $ac_status" >&5
+   echo "$as_me:11514: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11568,11 +11569,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11571: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11572: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11575: \$? = $ac_status" >&5
+   echo "$as_me:11576: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12937,7 +12938,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12940 "configure"
+#line 12941 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13035,7 +13036,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13038 "configure"
+#line 13039 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13920,11 +13921,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13923: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13924: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13927: \$? = $ac_status" >&5
+   echo "$as_me:13928: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13982,11 +13983,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13985: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13986: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13989: \$? = $ac_status" >&5
+   echo "$as_me:13990: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16104,11 +16105,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16107: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16108: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16111: \$? = $ac_status" >&5
+   echo "$as_me:16112: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16366,11 +16367,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16369: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16370: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16373: \$? = $ac_status" >&5
+   echo "$as_me:16374: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16428,11 +16429,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16431: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16432: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16435: \$? = $ac_status" >&5
+   echo "$as_me:16436: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18668,7 +18669,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18671 "configure"
+#line 18672 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18766,7 +18767,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18769 "configure"
+#line 18770 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20880,9 +20881,11 @@ sidtarget_arm=$sidtarget_default
 sidtarget_x86=$sidtarget_default
 sidtarget_mips=$sidtarget_default
 sidtarget_m32r=$sidtarget_default
-sidtarget_mt=$sidtarget_default
 sidtarget_m68k=$sidtarget_default
+sidtarget_mt=$sidtarget_default
 sidtarget_ppc=$sidtarget_default
+sidtarget_sh=$sidtarget_default
+sidtarget_sh64=$sidtarget_default
 sidtarget_xstormy16=$sidtarget_default
 
 for targ in $all_targets
@@ -20894,9 +20897,11 @@ do
       mips*)  sidtarget_mips=1 ;;
       m32r*)  sidtarget_m32r=1 ;;
       m68k*)  sidtarget_m68k=1 ;;
-      mt*) sidtarget_mt=1 ;;
+      mt*)    sidtarget_mt=1 ;;
       powerpc*) sidtarget_ppc=1 ;;
       ppc*)   sidtarget_ppc=1 ;;
+      sh64*) sidtarget_sh64=1 ;;
+      sh*) sidtarget_sh=1 ;;
       xstormy16*) sidtarget_xstormy16=1 ;;
       *)      { echo "$as_me:$LINENO: WARNING: \"Unknown target $targ\"" >&5
 echo "$as_me: WARNING: \"Unknown target $targ\"" >&2;} ;;
@@ -20911,6 +20916,8 @@ case 1 in
   ${sidtarget_m68k}) ;;
   ${sidtarget_mt}) ;;
   ${sidtarget_ppc}) ;;
+  ${sidtarget_sh}) ;;
+  ${sidtarget_sh64}) ;;
   ${sidtarget_xstormy16}) ;;
   *) { echo "$as_me:$LINENO: WARNING: No selected sid targets: use --enable-targets or --target" >&5
 echo "$as_me: WARNING: No selected sid targets: use --enable-targets or --target" >&2;}
@@ -21030,6 +21037,38 @@ fi
 echo "$as_me:$LINENO: result: $sidtarget_ppc" >&5
 echo "${ECHO_T}$sidtarget_ppc" >&6
 
+echo "$as_me:$LINENO: checking SH family support" >&5
+echo $ECHO_N "checking SH family support... $ECHO_C" >&6
+
+
+
+if test "x$sidtarget_sh" = x1; then
+  SIDTARGET_SH_TRUE=
+  SIDTARGET_SH_FALSE='#'
+else
+  SIDTARGET_SH_TRUE='#'
+  SIDTARGET_SH_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $sidtarget_sh" >&5
+echo "${ECHO_T}$sidtarget_sh" >&6
+
+echo "$as_me:$LINENO: checking SH64 family support" >&5
+echo $ECHO_N "checking SH64 family support... $ECHO_C" >&6
+
+
+
+if test "x$sidtarget_sh64" = x1; then
+  SIDTARGET_SH64_TRUE=
+  SIDTARGET_SH64_FALSE='#'
+else
+  SIDTARGET_SH64_TRUE='#'
+  SIDTARGET_SH64_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $sidtarget_sh64" >&5
+echo "${ECHO_T}$sidtarget_sh64" >&6
+
 echo "$as_me:$LINENO: checking Sanyo Xstormy16 family support" >&5
 echo $ECHO_N "checking Sanyo Xstormy16 family support... $ECHO_C" >&6
 
@@ -21071,6 +21110,13 @@ if test $sidtarget_mt -eq 1; then
 
 
 subdirs="$subdirs mt"
+
+fi
+if test $sidtarget_sh -eq 1 -o $sidtarget_sh64 -eq 1; then
+	cpu_subdirs="$cpu_subdirs sh"
+
+
+subdirs="$subdirs sh"
 
 fi
 if test $sidtarget_xstormy16 -eq 1; then
@@ -21551,6 +21597,20 @@ if test -z "${SIDTARGET_PPC_TRUE}" && test -z "${SIDTARGET_PPC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_PPC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"SIDTARGET_PPC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SIDTARGET_SH_TRUE}" && test -z "${SIDTARGET_SH_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_SH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SIDTARGET_SH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SIDTARGET_SH64_TRUE}" && test -z "${SIDTARGET_SH64_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SIDTARGET_SH64\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SIDTARGET_SH64\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22210,6 +22270,12 @@ s,@SIDTARGET_MT_FALSE@,$SIDTARGET_MT_FALSE,;t t
 s,@sidtarget_ppc@,$sidtarget_ppc,;t t
 s,@SIDTARGET_PPC_TRUE@,$SIDTARGET_PPC_TRUE,;t t
 s,@SIDTARGET_PPC_FALSE@,$SIDTARGET_PPC_FALSE,;t t
+s,@sidtarget_sh@,$sidtarget_sh,;t t
+s,@SIDTARGET_SH_TRUE@,$SIDTARGET_SH_TRUE,;t t
+s,@SIDTARGET_SH_FALSE@,$SIDTARGET_SH_FALSE,;t t
+s,@sidtarget_sh64@,$sidtarget_sh64,;t t
+s,@SIDTARGET_SH64_TRUE@,$SIDTARGET_SH64_TRUE,;t t
+s,@SIDTARGET_SH64_FALSE@,$SIDTARGET_SH64_FALSE,;t t
 s,@sidtarget_xstormy16@,$sidtarget_xstormy16,;t t
 s,@SIDTARGET_XSTORMY16_TRUE@,$SIDTARGET_XSTORMY16_TRUE,;t t
 s,@SIDTARGET_XSTORMY16_FALSE@,$SIDTARGET_XSTORMY16_FALSE,;t t
