* win/configure: Regenerated. Appears to have some stray 	conflict markers in it.

diff --git a/tix/win/configure b/tix/win/configure
--- a/tix/win/configure
+++ b/tix/win/configure
@@ -832,8 +832,6 @@ fi
 echo "$ac_t""$ac_cv_objext" 1>&6
 OBJEXT=$ac_cv_objext
 ac_objext=$ac_cv_objext
-<<<<<<< configure
-=======
 
 echo $ac_n "checking for Cygwin environment""... $ac_c" 1>&6
 echo "configure:838: checking for Cygwin environment" >&5
@@ -864,44 +862,13 @@ fi
 rm -f conftest*
 rm -f conftest*
 fi
->>>>>>> 1.1.1.2
 
-<<<<<<< configure
-NM=${NM-nm}
-=======
 echo "$ac_t""$ac_cv_cygwin" 1>&6
 CYGWIN=
 test "$ac_cv_cygwin" = yes && CYGWIN=yes
 CYGWIN=$ac_cv_cygwin
->>>>>>> 1.1.1.2
 
-<<<<<<< configure
-AS=${AS-as}
-=======
->>>>>>> 1.1.1.2
 
-<<<<<<< configure
-LD=${LD-ld}
-
-DLLTOOL=${DLLTOOL-dlltool}
-
-WINDRES=${WINDRES-windres}
-
-ac_aux_dir=
-for ac_dir in $srcdir $srcdir/.. $srcdir/../..; do
-  if test -f $ac_dir/install-sh; then
-    ac_aux_dir=$ac_dir
-    ac_install_sh="$ac_aux_dir/install-sh -c"
-    break
-  elif test -f $ac_dir/install.sh; then
-    ac_aux_dir=$ac_dir
-    ac_install_sh="$ac_aux_dir/install.sh -c"
-    break
-  fi
-done
-if test -z "$ac_aux_dir"; then
-  { echo "configure: error: can not find install-sh or install.sh in $srcdir $srcdir/.. $srcdir/../.." 1>&2; exit 1; }
-=======
 
 echo $ac_n "checking build system type""... $ac_c" 1>&6
 echo "configure:875: checking build system type" >&5
@@ -925,7 +892,6 @@ if test $host != $build; then
   ac_tool_prefix=${host_alias}-
 else
   ac_tool_prefix=
->>>>>>> 1.1.1.2
 fi
 
 # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
@@ -1361,10 +1327,6 @@ else
                 ac_cv_c_tclconfig=`(cd $srcdir/$i/unix; pwd)`
 	        break
             fi
-            if test -f $srcdir/$i/win/tclConfig.sh ; then
-                ac_cv_c_tclconfig=`(cd $srcdir/$i/win; pwd)`
-	        break
-            fi
         done
     fi
         if test x"${ac_cv_c_tclconfig}" = x ; then
@@ -1378,10 +1340,6 @@ else
                         for i in `ls -dr $tclconfpath/tcl* 2>/dev/null ` ; do
             if test -f $i/unix/tclConfig.sh ; then
                 ac_cv_c_tclconfig=`(cd $i/unix; pwd)`
-                break
-            fi
-            if test -f $i/win/tclConfig.sh ; then
-                ac_cv_c_tclconfig=`(cd $i/win; pwd)`
                 break
             fi
         done
@@ -1398,7 +1356,7 @@ fi
 	
     if test x"${ac_cv_c_tclconfig}" = x ; then
         TCLCONFIG=""
-        { echo "configure: error: Can't find Tcl configuration definitions" 1>&2; exit 1; }
+        echo "configure: warning: Can't find Tcl configuration definitions" 1>&2
     else
         no_tcl=""
         TCLCONFIG=${ac_cv_c_tclconfig}/tclConfig.sh
@@ -1441,11 +1399,7 @@ if test "${with_tkconfig+set}" = set; then
 fi
 
     echo $ac_n "checking for Tk configuration script""... $ac_c" 1>&6
-<<<<<<< configure
-echo "configure:978: checking for Tk configuration script" >&5
-=======
-echo "configure:1411: checking for Tk configuration script" >&5
->>>>>>> 1.1.1.2
+echo "configure:1403: checking for Tk configuration script" >&5
     if eval "test \"`echo '$''{'ac_cv_c_tkconfig'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1465,10 +1419,6 @@ else
                 ac_cv_c_tkconfig=`(cd $srcdir/$i/unix; pwd)`
 	        break
             fi
-            if test -f $srcdir/$i/win/tkConfig.sh ; then
-                ac_cv_c_tkconfig=`(cd $srcdir/$i/win; pwd)`
-	        break
-            fi
         done
     fi
         if test x"${ac_cv_c_tkconfig}" = x ; then
@@ -1482,10 +1432,6 @@ else
                         for i in `ls -dr $tkconfpath/tk* 2>/dev/null ` ; do
             if test -f $i/unix/tkConfig.sh ; then
                 ac_cv_c_tkconfig=`(cd $i/unix; pwd)`
-                break
-            fi
-            if test -f $i/win/tkConfig.sh ; then
-                ac_cv_c_tkconfig=`(cd $i/win; pwd)`
                 break
             fi
         done
@@ -1502,7 +1448,7 @@ fi
 	
     if test x"${ac_cv_c_tkconfig}" = x ; then
         TKCONFIG=""
-        { echo "configure: error: Can't find Tk configuration definitions" 1>&2; exit 1; }
+        echo "configure: warning: Can't find Tk configuration definitions" 1>&2
     else
         no_tk=""
         TKCONFIG=${ac_cv_c_tkconfig}/tkConfig.sh
@@ -1530,11 +1476,7 @@ fi
     
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-<<<<<<< configure
-echo "configure:1055: checking how to run the C preprocessor" >&5
-=======
-echo "configure:1496: checking how to run the C preprocessor" >&5
->>>>>>> 1.1.1.2
+echo "configure:1480: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -1549,21 +1491,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-<<<<<<< configure
-#line 1070 "configure"
-=======
-#line 1511 "configure"
->>>>>>> 1.1.1.2
+#line 1495 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-<<<<<<< configure
-{ (eval echo configure:1076: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-=======
-{ (eval echo configure:1517: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
->>>>>>> 1.1.1.2
+{ (eval echo configure:1501: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1574,21 +1508,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-<<<<<<< configure
-#line 1087 "configure"
-=======
-#line 1528 "configure"
->>>>>>> 1.1.1.2
+#line 1512 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-<<<<<<< configure
-{ (eval echo configure:1093: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-=======
-{ (eval echo configure:1534: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
->>>>>>> 1.1.1.2
+{ (eval echo configure:1518: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1599,21 +1525,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-<<<<<<< configure
-#line 1104 "configure"
-=======
-#line 1545 "configure"
->>>>>>> 1.1.1.2
+#line 1529 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-<<<<<<< configure
-{ (eval echo configure:1110: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-=======
-{ (eval echo configure:1551: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
->>>>>>> 1.1.1.2
+{ (eval echo configure:1535: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1641,11 +1559,7 @@ echo "$ac_t""$CPP" 1>&6
 dirlist=".. ../../ ../../../ ../../../../ ../../../../../ ../../../../../../ ../../../../../../.. ../../../../../../../.. ../../../../../../../../.. ../../../../../../../../../.."
 no_tcl=true
 echo $ac_n "checking for Tcl headers in the source tree""... $ac_c" 1>&6
-<<<<<<< configure
-echo "configure:1138: checking for Tcl headers in the source tree" >&5
-=======
-echo "configure:1579: checking for Tcl headers in the source tree" >&5
->>>>>>> 1.1.1.2
+echo "configure:1563: checking for Tcl headers in the source tree" >&5
 # Check whether --with-tclinclude or --without-tclinclude was given.
 if test "${with_tclinclude+set}" = set; then
   withval="$with_tclinclude"
@@ -1702,29 +1616,17 @@ if test x"${ac_cv_c_tclh}" = x ; then
    echo "$ac_t""none" 1>&6
    ac_safe=`echo "tcl.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for tcl.h""... $ac_c" 1>&6
-<<<<<<< configure
-echo "configure:1195: checking for tcl.h" >&5
-=======
-echo "configure:1636: checking for tcl.h" >&5
->>>>>>> 1.1.1.2
+echo "configure:1620: checking for tcl.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-<<<<<<< configure
-#line 1200 "configure"
-=======
-#line 1641 "configure"
->>>>>>> 1.1.1.2
+#line 1625 "configure"
 #include "confdefs.h"
 #include <tcl.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-<<<<<<< configure
-{ (eval echo configure:1205: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-=======
-{ (eval echo configure:1646: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
->>>>>>> 1.1.1.2
+{ (eval echo configure:1630: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1788,11 +1690,7 @@ fi
 dirlist=".. ../../ ../../../ ../../../../ ../../../../../ ../../../../../../ ../../../../../../.. ../../../../../../../.. ../../../../../../../../.. ../../../../../../../../../.."
 no_tk=true
 echo $ac_n "checking for Tk headers in the source tree""... $ac_c" 1>&6
-<<<<<<< configure
-echo "configure:1269: checking for Tk headers in the source tree" >&5
-=======
-echo "configure:1710: checking for Tk headers in the source tree" >&5
->>>>>>> 1.1.1.2
+echo "configure:1694: checking for Tk headers in the source tree" >&5
 # Check whether --with-tkinclude or --without-tkinclude was given.
 if test "${with_tkinclude+set}" = set; then
   withval="$with_tkinclude"
@@ -2098,7 +1996,6 @@ s%@TCL_LD_FLAGS@%$TCL_LD_FLAGS%g
 s%@TCL_LD_SEARCH_FLAGS@%$TCL_LD_SEARCH_FLAGS%g
 s%@TCL_RANLIB@%$TCL_RANLIB%g
 s%@TCL_BUILD_LIB_SPEC@%$TCL_BUILD_LIB_SPEC%g
-s%@TCL_BUILD_STUB_LIB_SPEC@%$TCL_BUILD_STUB_LIB_SPEC%g
 s%@TCL_LIB_SPEC@%$TCL_LIB_SPEC%g
 s%@TCL_BIN_DIR@%$TCL_BIN_DIR%g
 s%@TKCONFIG@%$TKCONFIG%g
@@ -2131,7 +2028,7 @@ cat >> $CONFIG_STATUS <<\EOF
 
 # Split the substitutions into bite-sized pieces for seds with
 # small command number limits, like on Digital OSF/1 and HP-UX.
-ac_max_sed_cmds=90 # Maximum number of lines to put in a sed script.
+ac_max_sed_cmds=60 # Maximum number of lines to put in a sed script.
 ac_file=1 # Number of current file.
 ac_beg=1 # First line for current file.
 ac_end=$ac_max_sed_cmds # Line after last line for current file.
