Track source location better, for better error messages. 	* pmacros.scm (-pmacro-eval): Delete, unused. 	(pmacro-expand, -pmacro-expand): New arg `loc', all callers updated. 	(-pmacro-expand-expr-list, -smacro-apply): Ditto. 	(scan-list, scan): Ditto. 	(-pmacro-builtin-pmacro, -pmacro-builtin-let, -pmacro-builtin-if, 	-pmacro-builtin-case, -pmacro-builtin-cond, -pmacro-builtin-begin, 	-pmacro-builtin-andif, -pmacro-builtin-orif): Ditto. 	(scan-list1): New function. 	(-pmacro-build-lambda): New arg `loc', all callers updated.  Rewrite. 	* read.scm (<reader>): New member `location'. 	(-reader-lookup-command): Renamed from reader-lookup-command, 	all callers updated. 	(reader-error): Rewrite to produce better source location info. 	(current-reader-location): New function. 	(-reader-process-expanded-1!): Renamed from -reader-process-expanded-1. 	All callers updated.  Record source location of expression. 	(reader-process-expanded!): Renamed from reader-process-expanded. 	All callers updated. 	(-reader-process!): Renamed from reader-process.  New arg `loc'. 	All callers updated.  Record source location of define-pmacro. 	* utils-cgen.scm (<location>): New class. 	(single-location): New (pseudo) class. 	(pretty-print-single-location, pretty-print-location): New functions. 	(location-top, location-push-single, location-push): New functions. 	(unspecified-location, current-input-location): New functions. 	(location-property): New object property. 	(location-property-set!): New function. 	(<source-ident>): Renamed from <ordered-ident>.  New member `location'. 	All uses updated. 	* testsuite/location-1.test: New testcase. 	* testsuite/run-tests.sh: Fix fail count handling. 	* testsuite/test-utils.sh.in (run_cgen): New option `-f'.  Allow tests 	to expect cgen to fail.
	* pmacros.scm (*): Use "pmacro" instead of "macro" more consistently.

	* read.scm (-cmd-include): Renamed from include.  All callers updated.
	(-cmd-if): Renamed from cmd-if.  All callers updated.
	Use reader-process-expanded! on then/else clauses instead of eval1.

diff --git a/cgen/testsuite/test-utils.sh.in b/cgen/testsuite/test-utils.sh.in
--- a/cgen/testsuite/test-utils.sh.in
+++ b/cgen/testsuite/test-utils.sh.in
@@ -31,17 +31,26 @@ rm -f ${tmp_match} ${tmp_expr}
 
 exit_code=0
 
+# Invoke this to run cgen.
+# Usage: run_cgen [-f] cpu-file-path
+# -f: cgen is expected to fail (useful for testing error handling)
+
 run_cgen() {
-    [ $# == 1 ] || { echo "missing cpu_file" >&2 ; exit 1 ; }
+    expect_fail=false
+    [ "$1" == "-f" ] && { expect_fail=true ; shift ; }
+
+    [ $# -ne 1 ] && { echo "missing cpu_file" >&2 ; exit 1 ; }
     cpu_file=$1
 
-    if ! ${GUILE} ${GUILEFLAGS} ${cgendir}/cgen-testsuite.scm \
+    if ${GUILE} ${GUILEFLAGS} ${cgendir}/cgen-testsuite.scm \
 	-s ${cgendir} \
 	-b ${CGENFLAGS} \
 	-a ${cpu_file} \
 	-T ${cgen_output_file} >& ${test_output_file}
     then
-	fail "${test} run of cgen"
+	${expect_fail} && { fail "${test} run of cgen expected to fail" ; }
+    else
+	${expect_fail} || { fail "${test} run of cgen" ; }
     fi
 }
 
